# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\abdul\Desktop\Gmonster (1)\warm_up_module_gmail\warm_up_module_gmail\ui\authentication.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 120)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: #eff2f8;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_sign_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sign_up.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_sign_up.setFont(font)
        self.pushButton_sign_up.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 5px;\n"
"    border-style: Solid;\n"
"    background:  rgb(255, 255, 255);\n"
"    padding: 5px 28px;\n"
"    color: #555;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:#acacac;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: #acacac;\n"
"    }")
        self.pushButton_sign_up.setObjectName("pushButton_sign_up")
        self.horizontalLayout.addWidget(self.pushButton_sign_up)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_sign_in = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sign_in.sizePolicy().hasHeightForWidth())
        self.pushButton_sign_in.setSizePolicy(sizePolicy)
        self.pushButton_sign_in.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_sign_in.setFont(font)
        self.pushButton_sign_in.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 5px;\n"
"    border-style: Solid;\n"
"    background:  rgb(255, 255, 255);\n"
"    padding: 5px 28px;\n"
"    color: #555;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:#acacac;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: #acacac;\n"
"    }")
        self.pushButton_sign_in.setObjectName("pushButton_sign_in")
        self.horizontalLayout.addWidget(self.pushButton_sign_in)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.statusbar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 2))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.statusbar.setStyleSheet("/* Base style for the progress bar */\n"
"QProgressBar {\n"
"    border: none;                   /* Remove border */\n"
"    border-radius: 2px;            /* Rounded corners */\n"
"    background-color: #E0E0E0;      /* Light gray background */\n"
"    text-align: center;             /* Center the text */\n"
"    color: transparent;  \n"
"    height: 2px;  \n"
"}\n"
"\n"
"/* Style for the progress chunk (filled part) */\n"
"QProgressBar::chunk {\n"
"    background-color: #3366FF;      /* Blue color for the progress */\n"
"    border-radius: 2px;            /* Match rounded corners */\n"
"}")
        self.statusbar.setProperty("value", 100)
        self.statusbar.setTextVisible(False)
        self.statusbar.setObjectName("statusbar")
        self.horizontalLayout_2.addWidget(self.statusbar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #555\n"
"}")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GMonster"))
        self.pushButton_sign_up.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton_sign_in.setText(_translate("MainWindow", "Log In"))
