# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 680))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #E3E3E3;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(240, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(280, 16777215))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
" background: qlineargradient(spread:pad,\n"
"                               x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #FFEFF2F8,\n"
"                               stop:1 #61BCD9EB);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setMinimumSize(QtCore.QSize(170, 110))
        self.label_3.setMaximumSize(QtCore.QSize(170, 110))
        self.label_3.setStyleSheet("image: url(:/logo/logo.png);\n"
"background: transparent;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget {\n"
"        background: transparent;\n"
"        border: none;\n"
"        outline: none;\n"
"    }\n"
"    QListWidget::item {\n"
"        background: transparent;\n"
"        padding: 12px 6px;\n"
"        font-size: 16px;\n"
"        color: #333;\n"
"    }\n"
"    QListWidget::item:selected {\n"
"        background: transparent;\n"
"        color: #000;\n"
"        font-weight: Black;\n"
"    }\n"
"\n"
"\n"
"\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f5f5f5;\n"
"                height: 12px;\n"
"                margin: 0px 12px 0px 12px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #888;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::handle:horizontal:hover {\n"
"                background: #666;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f5f5f5;\n"
"            }\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f5f5f5;\n"
"                width: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #888;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical:hover {\n"
"                background: #666;\n"
"            }\n"
"            QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #f5f5f5;\n"
"            }")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.widget_compose_mode = QtWidgets.QWidget(self.widget_2)
        self.widget_compose_mode.setVisible(False)
        self.widget_compose_mode.setStyleSheet("#widget_compose_mode {\n"
"    background: rgba(255, 255, 255, 0.28);\n"
"    border: 1px solid rgba(255, 255, 255, 0.45);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#frame_mode_toggle {\n"
"    background: rgba(255, 255, 255, 0.45);\n"
"    border-radius: 16px;\n"
"    border: 1px solid rgba(75, 125, 173, 0.35);\n"
"}\n"
"\n"
"QPushButton#pushButton_canned_mode,\n"
"QPushButton#pushButton_ai_mode {\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 14px;\n"
"    color: #444;\n"
"    font: 75 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton#pushButton_canned_mode:checked,\n"
"QPushButton#pushButton_ai_mode:checked {\n"
"    background: #4B7DAD;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton#pushButton_canned_mode:hover,\n"
"QPushButton#pushButton_ai_mode:hover {\n"
"    color: #000;\n"
"}")
        self.widget_compose_mode.setObjectName("widget_compose_mode")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_compose_mode)
        self.verticalLayout_3.setContentsMargins(14, 14, 14, 14)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_mode_heading = QtWidgets.QLabel(self.widget_compose_mode)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_mode_heading.setFont(font)
        self.label_mode_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mode_heading.setObjectName("label_mode_heading")
        self.verticalLayout_3.addWidget(self.label_mode_heading)
        self.frame_mode_toggle = QtWidgets.QFrame(self.widget_compose_mode)
        self.frame_mode_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mode_toggle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_mode_toggle.setObjectName("frame_mode_toggle")
        self.horizontalLayout_mode = QtWidgets.QHBoxLayout(self.frame_mode_toggle)
        self.horizontalLayout_mode.setContentsMargins(10, 6, 10, 6)
        self.horizontalLayout_mode.setSpacing(6)
        self.horizontalLayout_mode.setObjectName("horizontalLayout_mode")
        self.pushButton_canned_mode = QtWidgets.QPushButton(self.frame_mode_toggle)
        self.pushButton_canned_mode.setCheckable(True)
        self.pushButton_canned_mode.setChecked(True)
        self.pushButton_canned_mode.setObjectName("pushButton_canned_mode")
        self.horizontalLayout_mode.addWidget(self.pushButton_canned_mode)
        self.pushButton_ai_mode = QtWidgets.QPushButton(self.frame_mode_toggle)
        self.pushButton_ai_mode.setCheckable(True)
        self.pushButton_ai_mode.setObjectName("pushButton_ai_mode")
        self.horizontalLayout_mode.addWidget(self.pushButton_ai_mode)
        self.verticalLayout_3.addWidget(self.frame_mode_toggle)
        self.label_mode_hint = QtWidgets.QLabel(self.widget_compose_mode)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_mode_hint.setFont(font)
        self.label_mode_hint.setStyleSheet("color: #3c3c3c;")
        self.label_mode_hint.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mode_hint.setWordWrap(True)
        self.label_mode_hint.setObjectName("label_mode_hint")
        self.verticalLayout_3.addWidget(self.label_mode_hint)
        self.verticalLayout_2.addWidget(self.widget_compose_mode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("QWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }\n"
"\n"
"QToolButton {\n"
"    background: none;\n"
"    border: none;\n"
"    min-width: 0px;\n"
"    min-height: 0px;\n"
"    max-width: 0px;\n"
"    max-height: 0px;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    padding: 0px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setStyleSheet("background-color: #eff2f8;\n"
"")
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stackedWidgetPage1)
        self.verticalLayout.setContentsMargins(0, 0, 20, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_status = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_status.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: #555;")
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.widget_3 = QtWidgets.QWidget(self.stackedWidgetPage1)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.statusView = QtWidgets.QListView(self.widget_3)
        self.statusView.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        self.statusView.setFont(font)
        self.statusView.setStyleSheet("\n"
"\n"
"\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f5f5f5;\n"
"                height: 12px;\n"
"                margin: 0px 12px 0px 12px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #888;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::handle:horizontal:hover {\n"
"                background: #666;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f5f5f5;\n"
"            }\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f5f5f5;\n"
"                width: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #888;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical:hover {\n"
"                background: #666;\n"
"            }\n"
"            QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #f5f5f5;\n"
"            }")
        self.statusView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.statusView.setObjectName("statusView")
        self.horizontalLayout_4.addWidget(self.statusView)
        self.progress_bar_widget = QtWidgets.QWidget(self.widget_3)
        self.progress_bar_widget.setMinimumSize(QtCore.QSize(400, 0))
        self.progress_bar_widget.setObjectName("progress_bar_widget")
        self.horizontalLayout_4.addWidget(self.progress_bar_widget)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.stackedWidgetPage1)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.startButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: rgba(0, 138, 191);\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(0, 138, 191, 0.6);\n"
"    opacity: 0.2\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 138, 191);\n"
"    }")
        self.startButton.setFlat(False)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.cancelButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: rgba(0, 138, 191);\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(0, 138, 191, 0.6);\n"
"    opacity: 0.2\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 138, 191);\n"
"    }")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.widget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setStyleSheet("background-color: #fff;\n"
"")
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stackedWidgetPage2)
        self.gridLayout_3.setContentsMargins(20, 0, 20, 20)
        self.gridLayout_3.setSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        self.lineEdit_subject = QtWidgets.QLineEdit(self.stackedWidgetPage2)
        self.lineEdit_subject.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subject.setFont(font)
        self.lineEdit_subject.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.lineEdit_subject.setFrame(False)
        self.lineEdit_subject.setObjectName("lineEdit_subject")
        self.gridLayout_3.addWidget(self.lineEdit_subject, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 2, 0, 1, 1)
        self.textBrowser_body = QtWidgets.QTextBrowser(self.stackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser_body.sizePolicy().hasHeightForWidth())
        self.textBrowser_body.setSizePolicy(sizePolicy)
        self.textBrowser_body.setMinimumSize(QtCore.QSize(0, 320))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.textBrowser_body.setFont(font)
        self.textBrowser_body.setStyleSheet("\n"
"\n"
"QTextEdit{\n"
"    border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"color: #555;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f5f5f5;\n"
"                width: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #888;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical:hover {\n"
"                background: #666;\n"
"            }\n"
"            QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #f5f5f5;\n"
"            }")
        self.textBrowser_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_body.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser_body.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:14pt; color:#555555;\">{Hey|Hi|Hello} [TONAME],</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">I\'m reaching out to you because i {noticed|came across|found|visited} you website {the other day|yesterday} and thought you\'d be interested in a {collaboration|partnership}.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-size:14pt; color:#555555;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">{Hope you don\'t mind my outreach!|Looking forward to your reply!}</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">Regards,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; color:#555555;\">[FIRSTFROMNAME]</span></p></body></html>")
        self.textBrowser_body.setObjectName("textBrowser_body")
        self.gridLayout_3.addWidget(self.textBrowser_body, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 5, 0, 1, 1)
        self.pushButton_update_config = QtWidgets.QPushButton(self.stackedWidgetPage2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_update_config.setFont(font)
        self.pushButton_update_config.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: rgba(0, 138, 191);\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(0, 138, 191, 0.6);\n"
"    opacity: 0.2\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 138, 191);\n"
"    }")
        self.pushButton_update_config.setObjectName("pushButton_update_config")
        self.gridLayout_3.addWidget(self.pushButton_update_config, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.setRowStretch(4, 1)
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setStyleSheet("background-color: #eff2f8;\n"
"")
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stackedWidgetPage3)
        self.gridLayout_2.setContentsMargins(20, 0, 20, 20)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser_report = QtWidgets.QTextBrowser(self.stackedWidgetPage3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser_report.sizePolicy().hasHeightForWidth())
        self.textBrowser_report.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.textBrowser_report.setFont(font)
        self.textBrowser_report.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textBrowser_report.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_report.setObjectName("textBrowser_report")
        self.gridLayout_2.addWidget(self.textBrowser_report, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.stackedWidget.addWidget(self.stackedWidgetPage3)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WARM UP MODULE"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Main"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Compose"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Logs"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_mode_heading.setText(_translate("MainWindow", "AI / Canned Email Mode"))
        self.pushButton_canned_mode.setText(_translate("MainWindow", "Canned"))
        self.pushButton_ai_mode.setText(_translate("MainWindow", "AI"))
        self.label_mode_hint.setText(_translate("MainWindow", "AI mode locks the composer and uses the upcoming automated prompt."))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.lineEdit_subject.setText(_translate("MainWindow", "Just a friendly outreach about [3]"))
        self.pushButton_update_config.setText(_translate("MainWindow", "Update"))
import logo_rc
